apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-trace-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-demo
  template:
    metadata:
      labels:
        app: trace-demo
    spec:
      containers:
      - name: trace-demo-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/aiden-development-cluster/cloud-trace-demo:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: trace-demo
spec:
  type: LoadBalancer
  selector:
    app: trace-demo
  ports:
  - port: 80
    targetPort: 8080
